name: example
description: BLoC pattern samples.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_bloc_patterns:
    path: ../
  http: ^1.2.0
  infinite_widgets: ^2.0.2
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
flutter:
  uses-material-design: true
