name: example
description: BLoC pattern samples.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  connectivity_plus: ^4.0.1
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_bloc_patterns:
    path: ../
  http: ^1.0.0
  infinite_widgets: ^2.0.2
  lint: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
