name: flutter_bloc_patterns
description: A set of most common BLoC use cases build on top of flutter_bloc library.
version: 0.13.0
homepage: https://github.com/klisiewicz/flutter-bloc-patterns

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  bloc: ^8.1.3
  collection: ^1.18.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  meta: ^1.10.0

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
  mocktail: ^1.0.3
